apiVersion: v1
kind: ReplicationController
metadata:
  name: mysql-member
  namespace: openfx
spec:
  replicas: 1
  template:
    metadata:
      name: oauth2-db
      labels:
        app: oauht2-db
    spec:
      containers:
      - name: mysql
        image: mysql:5.7
        ports:
        - name: mysql-port
          containerPort: 3306
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: oauth2-db-secrets
                key: db-password
        volumeMounts:
        - mountPath: "/var/lib/mysql"
          name: mysql-storage
      volumes:
        - name: mysql-storage
          persistentVolumeClaim:
            claimName: mysql-pv-claim

