[[constraint]]
  name = "k8s.io/apimachinery"
  branch = "release-1.8"

[[constraint]]
  name = "k8s.io/client-go"
  version = "6.0.0"

[[constraint]]
  name = "github.com/golang/protobuf"
  version = "v1.1.0"

[[constraint]]
  name = "github.com/grpc-ecosystem/grpc-gateway"
  version = "v1.4.1"

[[constraint]]
  name = "google.golang.org/grpc"
  version = "v1.13.0"

[prune]
  go-tests = true
  unused-packages = true
