apiVersion: v1
kind: Secret
metadata:
  name: regcred
  namespace: openfx
data:
  .dockerconfigjson: eyJhdXRocyI6eyIxMC4wLjAuMjAyOjUwMDAiOnsidXNlcm5hbWUiOiJ0ZXN0IiwicGFzc3dvcmQiOiJ0ZXN0IiwiYXV0aCI6ImRHVnpkRHAwWlhOMCJ9fX0=
type: kubernetes.io/dockerconfigjson
---
apiVersion: v1
kind: Secret
metadata:
  name: regcred
  namespace: openfx-fn
data:
  .dockerconfigjson: eyJhdXRocyI6eyIxMC4wLjAuMjAyOjUwMDAiOnsidXNlcm5hbWUiOiJ0ZXN0IiwicGFzc3dvcmQiOiJ0ZXN0IiwiYXV0aCI6ImRHVnpkRHAwWlhOMCJ9fX0=
type: kubernetes.io/dockerconfigjson
