apiVersion: v1
kind: Secret
metadata:
  name: regcred
  namespace: openfx
data:
  .dockerconfigjson: eyJhdXRocyI6eyIxMC4wLjAuMTgwOjUwMDAiOnsidXNlcm5hbWUiOiJrZXRpIiwicGFzc3dvcmQiOiJrZXRpbGludXgiLCJhdXRoIjoiYTJWMGFUcHJaWFJwYkdsdWRYZz0ifX19
type: kubernetes.io/dockerconfigjson
---
apiVersion: v1
kind: Secret
metadata:
  name: regcred
  namespace: openfx-fn
data:
  .dockerconfigjson: eyJhdXRocyI6eyIxMC4wLjAuMTgwOjUwMDAiOnsidXNlcm5hbWUiOiJrZXRpIiwicGFzc3dvcmQiOiJrZXRpbGludXgiLCJhdXRoIjoiYTJWMGFUcHJaWFJwYkdsdWRYZz0ifX19
type: kubernetes.io/dockerconfigjson
