apiVersion: v1
kind: Service
metadata:
  name: oauth2-server
  namespace: openfx
  labels:
    app: oauth2-server
spec:
  type: NodePort
  ports:
    - port: 9096
      protocol: TCP
      targetPort: 9096
      nodePort: 30011
  selector:
    app: oauth2-server
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: oauth2-server
  namespace: openfx
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: oauth2-server
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
      - name: oauth2-server
        image: 10.0.0.91:5000/oauth2-server:0.1.0
        imagePullPolicy: Always
        env:
        - name: FUNCTION_NAMESPACE
          value: openfx-fn
        - name: IMAGE_PULL_POLICY
          value: "Always"
        ports:
        - containerPort: 9096
          protocol: TCP
